#!/usr/bin/env python
import subprocess
subprocess.call(["ls","-la"])

#command 1 to find sys info
uname = "uname"
uname_arg = "-a"

print "Gathering system information with %s command : \n" %uname
subprocess.call([uname, uname_arg])

#commmand 2 to find disk space
diskspace = "df"
diskspace_arg = "-h"
print "Gathering disk space information %s command \n" %diskspace
subprocess.call ([diskspace, diskspace_arg])




